// ============================================================================
// SPA RESERVATION SYSTEM - TYPESCRIPT TYPES & INTERFACES
// Matches Database Schema Exactly
// ============================================================================

// ============================================================================
// TYPE ALIASES
// ============================================================================

export type UserRole = 'member' | 'vip' | 'admin' | 'staff'

export type ServiceCategory = 
  | 'massage' 
  | 'spa' 
  | 'facial' 
  | 'body_wrap' 
  | 'nail_care' 
  | 'aromatherapy' 
  | 'bundle'

export type OrderStatus = 
  | 'pending' 
  | 'confirmed' 
  | 'completed' 
  | 'cancelled'

export type RoomStatus = 
  | 'available' 
  | 'cleaning' 
  | 'closed' 
  | 'reserved' 
  | 'maintenance'

export type PaymentMethod = 
  | 'credit_card' 
  | 'debit_card' 
  | 'cash' 
  | 'bank_transfer' 
  | 'gcash' 
  | 'paypal'

export type PaymentStatus = 
  | 'pending' 
  | 'completed' 
  | 'failed' 
  | 'refunded'

// ============================================================================
// USER INTERFACE
// ============================================================================

export interface User {
  // Auto-generated by Supabase Auth
  id: string

  // Personal Information
  firstName: string
  middleName?: string
  lastName: string
  emailAdd: string
  phoneNum?: string

  // Role & Permissions
  role: UserRole

  // Timestamps
  createdAt: string // ISO 8601 format
}

// Form data for creating/updating users
export interface UserFormData {
  firstName: string
  middleName?: string
  lastName: string
  emailAdd: string
  phoneNum?: string
  password?: string // Only for creation
  role: UserRole
}

// ============================================================================
// SERVICE INTERFACE
// ============================================================================

export interface Service {
  // Auto-generated by Supabase
  id: string

  // Service Details
  name: string
  category: ServiceCategory
  price: number
  description: string

  // Timestamps
  created: string // ISO 8601 format
}

// Form data for creating/updating services
export interface ServiceFormData {
  name: string
  category: ServiceCategory
  price: number
  description: string
}

// ============================================================================
// ROOM INTERFACE
// ============================================================================

export interface Room {
  // Auto-generated by Supabase
  id: string

  // Room Information
  name: string
  assignedId?: string // Staff ID managing this room
  assignedName?: string // Staff name for display
  isAvailable: RoomStatus // Status of the room

  // Timestamps
  createdAt: string // ISO 8601 format
  updatedAt: string // ISO 8601 format
}

// Form data for creating/updating rooms
export interface RoomFormData {
  name: string
  assignedId?: string
  isAvailable: RoomStatus
}

// ============================================================================
// ORDER INTERFACE
// ============================================================================

export interface Order {
  // Auto-generated by Supabase
  id: string

  // Order Information
  name: string
  clientId: string
  staffId?: string
  roomId?: string

  // Status & Total
  orderStatus: OrderStatus
  orderTotal: number // Auto-calculated from OrderItems

  // Related Data (joins)
  OrderItem?: OrderItem[]

  // Timestamps
  createdAt: string // ISO 8601 format
}

// Form data for creating orders
export interface OrderFormData {
  orderName: string
  clientId: string
  staffId?: string
  roomId?: string
  items: OrderItemInput[] // At least 1 item required
}

// ============================================================================
// ORDER ITEM INTERFACE
// ============================================================================

export interface OrderItem {
  // Auto-generated by Supabase
  id: string

  // Foreign Keys
  orderId: string
  serviceId: string

  // Item Details
  quantity: number
  priceAtPurchase: number // Locked-in price at time of purchase

  // Related Data (join)
  Service?: Service

  // Timestamps
  createdAt: string // ISO 8601 format
}

// Input data for adding items to order
export interface OrderItemInput {
  serviceId: string
  quantity: number // Default: 1
}

// ============================================================================
// RESERVATION INTERFACE
// ============================================================================

export interface Reservation {
  // Auto-generated by Supabase
  id: string

  // Reservation Information
  name: string
  clientId: string
  roomId: string
  staffId?: string

  // Reservation Time
  reservationTime: string // ISO 8601 format (datetime)

  // Timestamps
  createdAt: string // ISO 8601 format
}

// Form data for creating/updating reservations
export interface ReservationFormData {
  name: string
  clientId: string
  roomId: string
  staffId?: string
  reservationTime: string
}

// ============================================================================
// PAYMENT INTERFACE
// ============================================================================

export interface Payment {
  // Auto-generated by Supabase
  id: string

  // Foreign Keys
  orderId: string
  clientId: string

  // Payment Information
  amount: number
  paymentMethod: PaymentMethod
  paymentStatus: PaymentStatus

  // Reference & Tracking
  transactionId?: string // From payment gateway (Stripe, PayMongo, etc.)
  referenceNumber: string // Internal reference (e.g., PAY-2025-0001)

  // Timestamps
  paidAt?: string // When payment was completed
  createdAt: string // ISO 8601 format
  updatedAt: string // ISO 8601 format

  // Notes
  notes?: string // Admin notes about payment
}

// Form data for creating/updating payments
export interface PaymentFormData {
  orderId: string
  clientId: string
  amount: number
  paymentMethod: PaymentMethod
  transactionId?: string
  notes?: string
}

// ============================================================================
// API RESPONSE TYPES
// ============================================================================

export interface ApiResponse<T> {
  data: T | null
  error: string | null
}

export interface ApiListResponse<T> {
  data: T[]
  error: string | null
}

// ============================================================================
// DASHBOARD STATS TYPES
// ============================================================================

export interface DashboardStats {
  totalUsers: number
  activeRooms: number
  totalServices: number
  pendingOrders: number
}

export interface StatCard {
  label: string
  value: number | string
  icon: string
  color: string
}

export interface RecentActivity {
  id: number
  type: string
  description: string
  time: string
  status: 'success' | 'pending' | 'failed'
}

// ============================================================================
// FORM VALIDATION TYPES
// ============================================================================

export interface ValidationError {
  field: string
  message: string
}

export interface FormValidationResult {
  valid: boolean
  errors: ValidationError[]
}

// ============================================================================
// TABLE DATA TYPES
// ============================================================================

export interface TableColumn<T> {
  key: keyof T
  label: string
  sortable?: boolean
  searchable?: boolean
  render?: (value: any, row: T) => React.ReactNode
}

export interface TableState {
  sortBy?: string
  sortOrder?: 'asc' | 'desc'
  searchTerm?: string
  currentPage?: number
  pageSize?: number
}

// ============================================================================
// END OF TYPES & INTERFACES
// ============================================================================