// ==== DATATYPPES FOR DATABASE ====
// Aliases
export type UserType = "regular" | "vip"


export type OrderStatus = "pending" | "in_progress" | "completed" | "cancelled"


// ==== DEFINING TABLES ====
export interface User {

    // ID automatically generated by SUPABASE
    first_name: string,
    middle_name: string,
    last_name: string,
    email_address: string,
    phone_number: string,
    username: string,
    password: string,
    usertype: UserType,
    created_at: string // ISO DATE String

}

export interface Staff {

    // ID automatically generated by SUPABASE
    first_name: string,
    middle_name: string,
    last_name: string,
    email_address: string,
    phone_number: string,
    specialty: string,
    availability: boolean, // True if available, false if not, For Room Connection
    role: string
    username: string,
    password: string,
    created_at: string // ISO DATE String

}

export interface Service {

    // ID automatically generated by SUPABASE
    service_name: string,
    category: string,
    price: number,
    description: string,
    created_at: string // ISO DATE String

}


export interface Order {

    // ID automatically generated by SUPABASE
    order_name: string,
    user_id: number, // Foreign Key to Users Table
    service_id: number, // Foreign Key to Services Table
    staff_id: number, // Foreign Key to Staff Table
    order_status: OrderStatus,
    created_at: string // ISO DATE String

}


export interface Rooms {

    // ID automatically generated by SUPABASE
    room_number: string,
    assigned_staff_id: number, // Foreign Key to Staff Table
    assigned_staff_name: string, // For easier access to staff name without needing to join with Staff Table 
    availability: boolean, // True if available, false if not
    created_at: string // ISO DATE String

}

export interface Reservations {

    // ID automatically generated by SUPABASE
    reservation_name: string,
    user_id: number, // Foreign Key to Users Table
    order_id: number, // Foreign Key to Orders Table
    room_id: number, // Foreign Key to Rooms Table
    reservation_date: string, // ISO DATE String
    created_at: string // ISO DATE String

}